[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-mistral"
version = "0.15"
description = "LLM plugin providing access to Mistral models using the Mistral API"
readme = "README.md"
authors = [{name = "Simon Willison"}]
license = "Apache-2.0"
requires-python = ">=3.10"
classifiers = []
dependencies = [
    "llm>=0.32",
    "mistralai>=3.1.0",
]

[project.urls]
Homepage = "https://github.com/simonw/llm-mistral"
Changelog = "https://github.com/simonw/llm-mistral/releases"
Issues = "https://github.com/simonw/llm-mistral/issues"
CI = "https://github.com/simonw/llm-mistral/actions"

[project.entry-points.llm]
mistral = "llm_mistral"

[dependency-groups]
dev = ["cogapp", "pytest", "httpx2-pytest>=2.0.0", "pytest-asyncio"]

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
